name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    environment:
      name: pr-preview-${{ github.event.number }}
      url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-${{ github.event.number }}
    
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Prepare staging directory
        run: |
          mkdir -p staging/pr-${{ github.event.number }}
          cp -r ./* staging/pr-${{ github.event.number }}/ || true
          
          # Create index.html for preview directory listing
          cat > staging/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>MIAIGI PR Previews</title>
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; }
              h1 { color: #333; }
              .preview { background: #f8f9fa; padding: 20px; margin: 20px 0; border-radius: 8px; border-left: 4px solid #0969da; }
              .preview h3 { margin-top: 0; }
              .preview a { color: #0969da; text-decoration: none; font-weight: 500; }
              .preview a:hover { text-decoration: underline; }
              .meta { color: #656d76; font-size: 0.9em; }
            </style>
          </head>
          <body>
            <h1>🚀 MIAIGI PR Previews</h1>
            <p>This page lists all active pull request previews for testing changes before they go live.</p>
            
            <div class="preview">
              <h3>📱 PR #${{ github.event.number }}: Mobile UX Improvements</h3>
              <p><a href="./pr-${{ github.event.number }}/">→ View Preview</a></p>
              <p class="meta">
                <strong>Branch:</strong> ${{ github.event.pull_request.head.ref }}<br>
                <strong>Author:</strong> ${{ github.event.pull_request.user.login }}<br>
                <strong>Last Updated:</strong> $(date -u '+%Y-%m-%d %H:%M:%S UTC')
              </p>
            </div>
            
            <hr>
            <p><small>🔗 <a href="https://github.com/${{ github.repository }}">Back to Repository</a> | 🏠 <a href="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/">Live Site</a></small></p>
          </body>
          </html>
          EOF
      
      - name: Upload staging artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: staging
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-${{ github.event.number }}/';
            const body = `## 🚀 Preview Deployment Ready!
            
            Your changes have been deployed to a staging environment for testing:
            
            **📱 [View Preview →](${ previewUrl })**
            
            ### Testing Checklist:
            - [ ] Test mobile responsiveness (resize browser to 375px width)
            - [ ] Verify "Read More" buttons work correctly
            - [ ] Check content expansion/collapse functionality
            - [ ] Test on different screen sizes (mobile, tablet, desktop)
            - [ ] Verify all navigation links work
            - [ ] Check email links open correctly
            - [ ] Test "Return to top" button
            
            **Note:** This preview will be updated automatically when you push new commits to this PR.
            
            ---
            <details>
            <summary>📋 Preview Details</summary>
            
            - **URL:** ${ previewUrl }
            - **Branch:** \`${{ github.event.pull_request.head.ref }}\`
            - **Commit:** \`${{ github.event.pull_request.head.sha }}\`
            - **Deployed:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')
            
            </details>`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

  cleanup-preview:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Comment on closed PR
        uses: actions/github-script@v7
        with:
          script: |
            const body = `## 🗑️ Preview Environment Cleaned Up
            
            The staging preview for this PR has been removed since the PR was closed.
            
            **Live Site:** https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });